const splashTextCollection: string[] = [
  "Furfsky+ but its reborn",
  "bottem text",
  "The second era of Furfsky+",
  "undefined",
  "i wanted free vbucks :(",
  "reload for another message",
  "Yet another skyblock pack",
  "please stop posting furry images.",
  "boost the server for a cool role",
  "5261796D6F6E6420486F6C74",
  "46 75 72 66 53 6B 79 20 52 65 62 6F 72 6E",
  "B99S5E17",
  "Furfsky never dies",
  "skyblock nerds apps are open btw",
  "we're trying to get an ssl cert for https support please stop pestering us",
  "Avocados 🥑 from Mexico 🇲🇽",
  "the only cookies allowed on this website are booster cookies",
  "did you do your experiments yet?",
  "god i just hate reality",
  "We have a lot of e-girls here",
  "why does the discord server exist",
  "I purchased a baby clown from the Russian terrorist black market.",
  "I don’t support furry rights, but I do support this server",
  "even more cursed than the original!",
  '"For Furries by Furries"',
  "Furfsky reborn - now with more shit, just worse.",
  "Now with 56% more shitposting!",
  "“Is this the United Airlines costumer service center?”",
  "He stomped on his fruit loops and thus became a cereal killer.",
  "why do they call it oven if you oven the cold food of out hot eat the food",
  "Help im locked in a data center",
  "what",
  "Never half-ass two things. Whole-ass one thing.",
  "Now works with Wynncraft!",
  "i can smell your fear through the screen",
  "we will steal your ip and sell it to china",
  "we will steal your china and sell it to ip",
  "i haven't left my house since furf posted on the forums!",
  "i havent left my house, tyler refuses to let me out!",
  "help, im locked in the basement",
  "i havent left my house pls help me i'm hungry",
  "fuck",
  "Is this illegal?",
  "furryegirl",
  "furryeboy AR racing simulator",
  "oh no",
  "the pack that smiles back",
  "I regret joining",
  "this is the worst thing to happen to humanity",
  "Gib coin pls I new",
  "OMG YOUTUBER GIVE COIN!!!1!!!11111!!",
  "gif bezos",
  "Making websites is hard",
  "The fur-suit is mandatory",
  "you fool you blongus you absolute utter clampongus",
  "ooga booga",
  "If I drop soap on the ground, is the soap dirty, or am I utterly screwed?",
  "doodoo woohoo",
  "it do be like that",
  "furf is into mice",
];

export const useSplashText = () =>
  splashTextCollection[Math.floor(Math.random() * splashTextCollection.length)];
